export interface Photo {
  slug: string;
  alt: string;
  aspect: "portrait" | "landscape" | "square";
  featured?: boolean;
}

export const photos: Photo[] = [
  { slug: "photo-001", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-002", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-003", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-004", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-005", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-006", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-007", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-008", alt: "Documentary eye, editorial finish", aspect: "portrait" },
  { slug: "photo-009", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-010", alt: "Quiet composition, honest detail", aspect: "square", featured: true },
  { slug: "photo-011", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-012", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-013", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-014", alt: "Texture and tone, on location", aspect: "landscape", featured: true },
  { slug: "photo-015", alt: "Minimal frame, maximum light", aspect: "portrait" },
  { slug: "photo-016", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-017", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-018", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-019", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-020", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-021", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-022", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-023", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-024", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-025", alt: "Natural light, unposed moment", aspect: "portrait", featured: true },
  { slug: "photo-026", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-027", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-028", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-029", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-030", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-031", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-032", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-033", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-034", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-035", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-036", alt: "Study in light and shadow", aspect: "portrait" },
  { slug: "photo-037", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-038", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-039", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-040", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-041", alt: "Natural light, unposed moment", aspect: "landscape", featured: true },
  { slug: "photo-042", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-043", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-044", alt: "Study in light and shadow", aspect: "portrait" },
  { slug: "photo-045", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-046", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-047", alt: "Minimal frame, maximum light", aspect: "portrait", featured: true },
  { slug: "photo-048", alt: "Documentary eye, editorial finish", aspect: "portrait" },
  { slug: "photo-049", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-050", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-051", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-052", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-053", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-054", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-055", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-056", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-057", alt: "Natural light, unposed moment", aspect: "portrait" },
  { slug: "photo-058", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-059", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-060", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-061", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-062", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-063", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-064", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-065", alt: "Natural light, unposed moment", aspect: "portrait", featured: true },
  { slug: "photo-066", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-067", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-068", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-069", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-070", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-071", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-072", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-073", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-074", alt: "Quiet composition, honest detail", aspect: "landscape", featured: true },
  { slug: "photo-075", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-076", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-077", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-078", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-079", alt: "Minimal frame, maximum light", aspect: "landscape", featured: true },
  { slug: "photo-080", alt: "Documentary eye, editorial finish", aspect: "portrait" },
  { slug: "photo-081", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-082", alt: "Quiet composition, honest detail", aspect: "portrait" },
  { slug: "photo-083", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-084", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-085", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-086", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-087", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-088", alt: "Documentary eye, editorial finish", aspect: "landscape" },
  { slug: "photo-089", alt: "Natural light, unposed moment", aspect: "landscape" },
  { slug: "photo-090", alt: "Quiet composition, honest detail", aspect: "landscape" },
  { slug: "photo-091", alt: "Candid frame, available light", aspect: "landscape" },
  { slug: "photo-092", alt: "Study in light and shadow", aspect: "landscape" },
  { slug: "photo-093", alt: "A moment, held still", aspect: "landscape" },
  { slug: "photo-094", alt: "Texture and tone, on location", aspect: "landscape" },
  { slug: "photo-095", alt: "Minimal frame, maximum light", aspect: "landscape" },
  { slug: "photo-096", alt: "Documentary eye, editorial finish", aspect: "portrait" },
  { slug: "photo-097", alt: "Natural light, unposed moment", aspect: "landscape" },
];

export const featuredPhotos = photos.filter((p) => p.featured);
