export interface Photo {
  slug: string;
  alt: string;
  aspect: "portrait" | "landscape" | "square";
  featured?: boolean;
}

export const photos: Photo[] = [
  { slug: "photo-001", alt: "Photograph 1", aspect: "landscape", featured: true },
  { slug: "photo-002", alt: "Photograph 2", aspect: "landscape" },
  { slug: "photo-003", alt: "Photograph 3", aspect: "landscape" },
  { slug: "photo-004", alt: "Photograph 4", aspect: "landscape" },
  { slug: "photo-005", alt: "Photograph 5", aspect: "landscape" },
  { slug: "photo-006", alt: "Photograph 6", aspect: "landscape" },
  { slug: "photo-007", alt: "Photograph 7", aspect: "landscape" },
  { slug: "photo-008", alt: "Photograph 8", aspect: "portrait" },
  { slug: "photo-009", alt: "Photograph 9", aspect: "landscape" },
  { slug: "photo-010", alt: "Photograph 10", aspect: "square" },
  { slug: "photo-011", alt: "Photograph 11", aspect: "landscape" },
  { slug: "photo-012", alt: "Photograph 12", aspect: "landscape" },
  { slug: "photo-013", alt: "Photograph 13", aspect: "landscape", featured: true },
  { slug: "photo-014", alt: "Photograph 14", aspect: "landscape" },
  { slug: "photo-015", alt: "Photograph 15", aspect: "portrait" },
  { slug: "photo-016", alt: "Photograph 16", aspect: "landscape" },
  { slug: "photo-017", alt: "Photograph 17", aspect: "landscape" },
  { slug: "photo-018", alt: "Photograph 18", aspect: "landscape" },
  { slug: "photo-019", alt: "Photograph 19", aspect: "landscape" },
  { slug: "photo-020", alt: "Photograph 20", aspect: "landscape" },
  { slug: "photo-021", alt: "Photograph 21", aspect: "landscape" },
  { slug: "photo-022", alt: "Photograph 22", aspect: "landscape" },
  { slug: "photo-023", alt: "Photograph 23", aspect: "landscape" },
  { slug: "photo-024", alt: "Photograph 24", aspect: "landscape" },
  { slug: "photo-025", alt: "Photograph 25", aspect: "portrait", featured: true },
  { slug: "photo-026", alt: "Photograph 26", aspect: "landscape" },
  { slug: "photo-027", alt: "Photograph 27", aspect: "landscape" },
  { slug: "photo-028", alt: "Photograph 28", aspect: "landscape" },
  { slug: "photo-029", alt: "Photograph 29", aspect: "landscape" },
  { slug: "photo-030", alt: "Photograph 30", aspect: "landscape" },
  { slug: "photo-031", alt: "Photograph 31", aspect: "landscape" },
  { slug: "photo-032", alt: "Photograph 32", aspect: "landscape" },
  { slug: "photo-033", alt: "Photograph 33", aspect: "landscape" },
  { slug: "photo-034", alt: "Photograph 34", aspect: "landscape" },
  { slug: "photo-035", alt: "Photograph 35", aspect: "landscape" },
  { slug: "photo-036", alt: "Photograph 36", aspect: "portrait" },
  { slug: "photo-037", alt: "Photograph 37", aspect: "landscape", featured: true },
  { slug: "photo-038", alt: "Photograph 38", aspect: "landscape" },
  { slug: "photo-039", alt: "Photograph 39", aspect: "landscape" },
  { slug: "photo-040", alt: "Photograph 40", aspect: "landscape" },
  { slug: "photo-041", alt: "Photograph 41", aspect: "landscape" },
  { slug: "photo-042", alt: "Photograph 42", aspect: "landscape" },
  { slug: "photo-043", alt: "Photograph 43", aspect: "landscape" },
  { slug: "photo-044", alt: "Photograph 44", aspect: "portrait" },
  { slug: "photo-045", alt: "Photograph 45", aspect: "landscape" },
  { slug: "photo-046", alt: "Photograph 46", aspect: "landscape" },
  { slug: "photo-047", alt: "Photograph 47", aspect: "portrait" },
  { slug: "photo-048", alt: "Photograph 48", aspect: "portrait" },
  { slug: "photo-049", alt: "Photograph 49", aspect: "landscape", featured: true },
  { slug: "photo-050", alt: "Photograph 50", aspect: "landscape" },
  { slug: "photo-051", alt: "Photograph 51", aspect: "landscape" },
  { slug: "photo-052", alt: "Photograph 52", aspect: "landscape" },
  { slug: "photo-053", alt: "Photograph 53", aspect: "landscape" },
  { slug: "photo-054", alt: "Photograph 54", aspect: "landscape" },
  { slug: "photo-055", alt: "Photograph 55", aspect: "landscape" },
  { slug: "photo-056", alt: "Photograph 56", aspect: "landscape" },
  { slug: "photo-057", alt: "Photograph 57", aspect: "portrait" },
  { slug: "photo-058", alt: "Photograph 58", aspect: "landscape" },
  { slug: "photo-059", alt: "Photograph 59", aspect: "landscape" },
  { slug: "photo-060", alt: "Photograph 60", aspect: "landscape" },
  { slug: "photo-061", alt: "Photograph 61", aspect: "landscape", featured: true },
  { slug: "photo-062", alt: "Photograph 62", aspect: "landscape" },
  { slug: "photo-063", alt: "Photograph 63", aspect: "landscape" },
  { slug: "photo-064", alt: "Photograph 64", aspect: "landscape" },
  { slug: "photo-065", alt: "Photograph 65", aspect: "portrait" },
  { slug: "photo-066", alt: "Photograph 66", aspect: "landscape" },
  { slug: "photo-067", alt: "Photograph 67", aspect: "landscape" },
  { slug: "photo-068", alt: "Photograph 68", aspect: "landscape" },
  { slug: "photo-069", alt: "Photograph 69", aspect: "landscape" },
  { slug: "photo-070", alt: "Photograph 70", aspect: "landscape" },
  { slug: "photo-071", alt: "Photograph 71", aspect: "landscape" },
  { slug: "photo-072", alt: "Photograph 72", aspect: "landscape" },
  { slug: "photo-073", alt: "Photograph 73", aspect: "landscape", featured: true },
  { slug: "photo-074", alt: "Photograph 74", aspect: "landscape" },
  { slug: "photo-075", alt: "Photograph 75", aspect: "landscape" },
  { slug: "photo-076", alt: "Photograph 76", aspect: "landscape" },
  { slug: "photo-077", alt: "Photograph 77", aspect: "landscape" },
  { slug: "photo-078", alt: "Photograph 78", aspect: "landscape" },
  { slug: "photo-079", alt: "Photograph 79", aspect: "landscape" },
  { slug: "photo-080", alt: "Photograph 80", aspect: "portrait" },
  { slug: "photo-081", alt: "Photograph 81", aspect: "landscape" },
  { slug: "photo-082", alt: "Photograph 82", aspect: "portrait" },
  { slug: "photo-083", alt: "Photograph 83", aspect: "landscape" },
  { slug: "photo-084", alt: "Photograph 84", aspect: "landscape" },
  { slug: "photo-085", alt: "Photograph 85", aspect: "landscape", featured: true },
  { slug: "photo-086", alt: "Photograph 86", aspect: "landscape" },
  { slug: "photo-087", alt: "Photograph 87", aspect: "landscape" },
  { slug: "photo-088", alt: "Photograph 88", aspect: "landscape" },
  { slug: "photo-089", alt: "Photograph 89", aspect: "landscape" },
  { slug: "photo-090", alt: "Photograph 90", aspect: "landscape" },
  { slug: "photo-091", alt: "Photograph 91", aspect: "landscape" },
  { slug: "photo-092", alt: "Photograph 92", aspect: "landscape" },
  { slug: "photo-093", alt: "Photograph 93", aspect: "landscape" },
  { slug: "photo-094", alt: "Photograph 94", aspect: "landscape" },
  { slug: "photo-095", alt: "Photograph 95", aspect: "landscape" },
  { slug: "photo-096", alt: "Photograph 96", aspect: "portrait" },
  { slug: "photo-097", alt: "Photograph 97", aspect: "landscape" },
];

export const featuredPhotos = photos.filter((p) => p.featured);
