export interface Photo {
  slug: string;
  alt: string;
  aspect: "portrait" | "landscape" | "square";
  ratio: number;
  featured?: boolean;
}

export const heroPhoto: Photo = { slug: "photo-067", alt: "Featured photograph", aspect: "landscape", ratio: 1.4993 };

export const photos: Photo[] = [
  { slug: "photo-001", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.6065 },
  { slug: "photo-002", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5224 },
  { slug: "photo-003", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.5238 },
  { slug: "photo-004", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-005", alt: "A moment, held still", aspect: "landscape", ratio: 1.5238 },
  { slug: "photo-009", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-010", alt: "Minimal frame, maximum light", aspect: "portrait", ratio: 0.6409, featured: true },
  { slug: "photo-011", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5209 },
  { slug: "photo-012", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.4993 },
  { slug: "photo-013", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5256 },
  { slug: "photo-014", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.3333, featured: true },
  { slug: "photo-015", alt: "Study in light and shadow", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-016", alt: "A moment, held still", aspect: "landscape", ratio: 1.5224 },
  { slug: "photo-017", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5260 },
  { slug: "photo-018", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5246 },
  { slug: "photo-019", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5275 },
  { slug: "photo-021", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-022", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-023", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.5253 },
  { slug: "photo-024", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-025", alt: "A moment, held still", aspect: "portrait", ratio: 0.7500, featured: true },
  { slug: "photo-026", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-027", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-028", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-029", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.5209 },
  { slug: "photo-030", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-031", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-032", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-036", alt: "A moment, held still", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-037", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-038", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.7022 },
  { slug: "photo-039", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-040", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-041", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.4986, featured: true },
  { slug: "photo-042", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-043", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-044", alt: "A moment, held still", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-045", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5209 },
  { slug: "photo-046", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-047", alt: "Documentary eye, editorial finish", aspect: "portrait", ratio: 0.7500, featured: true },
  { slug: "photo-048", alt: "Natural light, unposed moment", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-049", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-050", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-051", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-052", alt: "A moment, held still", aspect: "landscape", ratio: 1.5216 },
  { slug: "photo-054", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5253 },
  { slug: "photo-055", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-056", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-057", alt: "Natural light, unposed moment", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-059", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-061", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-062", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-063", alt: "A moment, held still", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-064", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-065", alt: "Minimal frame, maximum light", aspect: "portrait", ratio: 0.7500 },
  { slug: "photo-066", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5224 },
  { slug: "photo-072", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-073", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5246 },
  { slug: "photo-074", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.3333, featured: true },
  { slug: "photo-075", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-076", alt: "A moment, held still", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-077", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5209 },
  { slug: "photo-078", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-079", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.3333 },
  { slug: "photo-080", alt: "Natural light, unposed moment", aspect: "portrait", ratio: 0.7500 },
  { slug: "photo-081", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-082", alt: "Candid frame, available light", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-084", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-085", alt: "A moment, held still", aspect: "landscape", ratio: 2.2758 },
  { slug: "photo-086", alt: "Texture and tone, on location", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-087", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-088", alt: "Documentary eye, editorial finish", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-089", alt: "Natural light, unposed moment", aspect: "landscape", ratio: 1.3333 },
  { slug: "photo-090", alt: "Quiet composition, honest detail", aspect: "landscape", ratio: 1.5187 },
  { slug: "photo-092", alt: "Candid frame, available light", aspect: "landscape", ratio: 1.4972 },
  { slug: "photo-094", alt: "Study in light and shadow", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-095", alt: "A moment, held still", aspect: "landscape", ratio: 1.5000 },
  { slug: "photo-096", alt: "Texture and tone, on location", aspect: "portrait", ratio: 0.6667 },
  { slug: "photo-097", alt: "Minimal frame, maximum light", aspect: "landscape", ratio: 1.5000 },
];

export const featuredPhotos = photos.filter((p) => p.featured);
